// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
	aws_project_region: "us-east-2",
	aws_cognito_identity_pool_id:
		"us-west-2:5b369d62-2db7-40da-a048-83dc503fca09",
	aws_cognito_region: "us-east-2",
	aws_user_pools_id: "us-west-2_vjBFE3x9V",
	aws_user_pools_web_client_id: "66fg3a0htj89baunuvfk2d2luf"
};

export default awsmobile;
