export default {
	//Ui
	TOGGLE_CART: "TOGGLE_CART",

	//Metadata
	FETCH_YEARS_SUCCESS: "FETCH_YEARS_SUCCESS",
	FETCH_YEARS_FAILURE: "FETCH_YEARS_FAILURE",
	FETCH_MAKES_SUCCESS: "FETCH_MAKES_SUCCESS",
	FETCH_MAKES_FAILURE: "FETCH_MAKES_FAILURE",
	FETCH_MAKES_LOADING: "FETCH_MAKES_LOADING",
	FETCH_MODELS_SUCCESS: "FETCH_MODELS_SUCCESS",
	FETCH_MODELS_FAILURE: "FETCH_MODELS_FAILURE",
	FETCH_MODELS_LOADING: "FETCH_MODELS_LOADING",
	FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
	FETCH_CATEGORIES_FAILURE: "FETCH_CATEGORIES_FAILURE",

	//Settings
	FETCH_SETTINGS_SUCCESS: "FETCH_SETTINGS_SUCCESS",
	FETCH_SETTINGS_FAILURE: "FETCH_SETTINGS_FAILURE",

	//Pages
	FETCH_PAGES_SUCCESS: "FETCH_PAGES_SUCCESS",
	FETCH_PAGES_FAILURE: "FETCH_PAGES_FAILURE",

	//Data
	FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
	FETCH_PRODUCTS__FAILURE: "FETCH_PRODUCTS_FAILURE",
	SEARCH_CRITERIA: "SEARCH_CRITERIA",

	//Order
	UPDATE_ORDER: "UPDATE_ORDER",
	UPDATE_CART: "UPDATE_CART"
};
